optimize fastq-linking code

diff --git a/code/run_fastq-link b/code/run_fastq-link
--- a/code/run_fastq-link
+++ b/code/run_fastq-link
@@ -11,9 +11,6 @@ source code/custom_bash_profile	# shell settings
 if [ "$#" -lt 3 ]; then
 	printf "\n\n###### Usage\n\n"
 	printf "$0 <PARAMS file> <OUTPUT_DIR> <INPUT_DIR> [Optional: Sample Name] \n\n"
-	printf "Attention: "
-	printf "	For SRA download file link, the INPUT_DIR is the download DIR, and PARAMS file should have \"SRA\" as parameter\n\n"
-	printf "	For GTC local sample, the INPUT_DIR is the meta_data DIR, and the PARAMS file should have \"GTC\" as parameter\n\n"
 	exit
 fi
 
@@ -35,76 +32,18 @@ SAMPLE=$4
 
 IFS=$'\n'
 
-params=`cat $PARAMS | grep -P "^fastq-link\t" | cut -f2`
+params=`cat $PARAMS | grep -P "^fastq-link\t" | cut -f2 | tr ' ' '\n' | grep -v "^#"`
 
 #########################
 # read input
-
 if [ ! -z "`cat $PARAMS | grep -P "^fastq-link\t"`" ]
 then
 
-FLAG=0
-if [ -f $INP_DIR/meta_data/sra_info.txt ] && [ $params == "SRA" ]
-then
-#########################
-# For SRA Download
-for record in `cat $INP_DIR/meta_data/sra_info.txt | grep SRX` 
+for FILE in $params
 do
-	FLAG=1
-	name_sample=`echo $record | cut -f1`
-	id_sample=`echo $record | cut -f2`
-if [ "$name_sample" == "$SAMPLE" ] || [ -z "$SAMPLE" ]
-then
-	link_sample="ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByExp/sra/SRX/${id_sample:0:6}/$id_sample/"
-	ID_RUNS=(`curl -sS $link_sample | sed -r 's/\s+/\t/g' | cut -f9 `)
-	num_run=0
-
-
-#########################
-# check for output existance
-	if [ ! -d $INP_DIR/$name_sample ]
+	mylink=`head -1 $FILE`
+	if [ -d $mylink ]
 	then
-		printf "\n\nERROR! $INP_DIR/${name_sample} not found!\n\n"
-		exit 1
-	fi
-	
-	if [ ! -d $OUT_DIR/$name_sample ]
-	then
-		mkdir $OUT_DIR/$name_sample
-	fi
-
-
-	for id_run in "${ID_RUNS[@]}"
-	do
-		((num_run++))
-		num_run=$(printf "%03d" $num_run)
-		link_run=${link_sample}${id_run}"/" 
-		ID_FILES=(`curl -sS $link_run | sed -r 's/\s+/\t/g' | cut -f9 `)
-		num_read=0
-		for name_file in "${ID_FILES[@]}"
-		do
-			link_file=${link_run}${name_file}"/"
-			id_file=${name_file%.*}
-
-printf "\n\n***** Linking $name_sample To $INP_DIR/$name_sample/${id_file}...\n"
-
-ln -sf ../`basename $INP_DIR`/$name_sample/${id_file}_1.fastq.gz $OUT_DIR/$name_sample/${name_sample}_L${num_run}_R1.fastq.gz
-if [[ -f ../`basename $INP_DIR`/$name_sample/${id_file}_2.fastq.gz ]]
-then
-ln -sf ../`basename $INP_DIR`/$name_sample/${id_file}_2.fastq.gz $OUT_DIR/$name_sample/${name_sample}_L${num_run}_R2.fastq.gz
-fi
-
-		done
-	done
-fi
-done
-
-elif [ -f `ls $INP_DIR/meta_data/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].txt | head -1` ] && [ $params == "GTC" ]
-then
-	FLAG=1
-	for FILE in `ls $INP_DIR/meta_data/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].txt`
-	do
-		mylink=`head -1 $FILE`
 		dirname=`basename $FILE | sed 's/.txt//g'`
 		ln -s $mylink $OUT_DIR/$dirname
 		for record in `cat $FILE | grep -v "\/"`
@@ -125,21 +64,68 @@ then
 				done
 			fi			
 		done
-	done
 
-else
-	echo
-fi
-
-fi
-
-if [ $FLAG -ne 1 ]
+##########################
+# for SRA download linking
+	elif [ ! -z `cat $FILE | cut -f2 | grep SRX | tr '\n' 'XXXX'` ]
+	then
+		
+for record in `cat $FILE | grep SRX`
+do
+        name_sample=`echo $record | cut -f1`
+        id_sample=`echo $record | cut -f2`
+if [ "$name_sample" == "$SAMPLE" ] || [ -z "$SAMPLE" ]
 then
-	printf "\n\nERROR in INPUT file!\n\n"
-	exit 1
+        link_sample="ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByExp/sra/SRX/${id_sample:0:6}/$id_sample/"
+        ID_RUNS=(`curl -sS $link_sample | sed -r 's/\s+/\t/g' | cut -f9 `)
+        num_run=0
+
+
+#########################
+# check if SRA download complete
+        if [ ! -d $INP_DIR/$name_sample ]
+        then
+                printf "\n\nERROR! $INP_DIR/${name_sample} not found!\n\n"
+                exit 1
+        fi
+
+        if [ ! -d $OUT_DIR/$name_sample ]
+        then
+                mkdir $OUT_DIR/$name_sample
+        fi
+
+
+        for id_run in "${ID_RUNS[@]}"
+        do
+                ((num_run++))
+                num_run=$(printf "%03d" $num_run)
+                link_run=${link_sample}${id_run}"/"
+                ID_FILES=(`curl -sS $link_run | sed -r 's/\s+/\t/g' | cut -f9 `)
+                num_read=0
+                for name_file in "${ID_FILES[@]}"
+                do
+                        link_file=${link_run}${name_file}"/"
+                        id_file=${name_file%.*}
+
+printf "\n\n***** Linking $name_sample To $INP_DIR/$name_sample/${id_file}...\n"
+
+ln -sf ../`basename $INP_DIR`/$name_sample/${id_file}_1.fastq.gz $OUT_DIR/$name_sample/${name_sample}_L${num_run}_R1.fastq.gz
+if [[ -f ../`basename $INP_DIR`/$name_sample/${id_file}_2.fastq.gz ]]
+then
+ln -sf ../`basename $INP_DIR`/$name_sample/${id_file}_2.fastq.gz $OUT_DIR/$name_sample/${name_sample}_L${num_run}_R2.fastq.gz
 fi
 
-params=""
+                done
+        done
+fi
+done
+	else
+		printf "\n\nERROR in INPUT file!\n\n"
+		exit 1
+	fi
+done
+
+fi
 
 #########################
 date
